### ISSUE TITLE
aspx在列目录的时候会报错

### ISSUE THREAD

**Issue by 0xa-saline** [x1a0t/Behinder-Source#3]
aspx在列目录的时候会提示

org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:507)
	at org.json.JSONObject.<init>(JSONObject.java:222)
	at org.json.JSONObject.<init>(JSONObject.java:406)
	at net.rebeyond.behinder.core.ShellService.listFiles(ShellService.java:459)
	at net.rebeyond.behinder.ui.controller.FileManagerViewController.lambda$expandByPath$24(FileManagerViewController.java:554)
	at java.lang.Thread.run(Thread.java:748)

jsp不会出现这个问题.php和asp没测试

**Comment by x1a0t** [comment]
aspx的其他功能正常吗？因为我本地没啥问题哈，请问你的环境是？

**Comment by 0xa-saline** [comment]
其他的正常，就是列目录不行。windows 2008 r2+iis7.5 原本是正常的
